plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-rspec_rails
  - rubocop-slim

AllCops:
  NewCops: enable

#Temporarily
Style/Documentation:
  Enabled: false
