default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: focus_time_development
  username: postgres
  password:

test:
  <<: *default
  database: focus_time_test
  username: postgres
  password:

production:
  primary: &primary_production
    <<: *default
    database: focus_time_production
    username: <%= ENV["FOCUS_TIME_DATABASE_USER"] %>
    password: <%= ENV["FOCUS_TIME_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: focus_time_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: focus_time_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: focus_time_production_cable
    migrations_paths: db/cable_migrate
