name: Slim Lint

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  slim-lint:
    name: Run Slim Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      
      - name: Install dependencies
        run: bundle install
    
      - name: Run Slim Lint
        run: bundle exec slim-lint app/views
